/*
 *
 * Copyright (c) 2024 The ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 */

#pragma once

#include <lvgl.h>
#include <zephyr/kernel.h>

#define CANVAS_WIDTH IS_ENABLED(CONFIG_DONGLE_DISPLAY_ROTATE) \
            ? CONFIG_DONGLE_DISPLAY_ORIGINAL_HEIGHT \
            : CONFIG_DONGLE_DISPLAY_ORIGINAL_WIDTH
#define CANVAS_HEIGHT IS_ENABLED(CONFIG_DONGLE_DISPLAY_ROTATE) \
            ? CONFIG_DONGLE_DISPLAY_ORIGINAL_WIDTH \
            : CONFIG_DONGLE_DISPLAY_ORIGINAL_HEIGHT

#define ROTATION IS_ENABLED(CONFIG_DONGLE_DISPLAY_ROTATE) ? 900 : 0
#define ORIENTATION IS_ENABLED(CONFIG_DONGLE_DISPLAY_FLIP) ? 1800 : 0

#define LVGL_BACKGROUND IS_ENABLED(CONFIG_DONGLE_DISPLAY_INVERT) ? lv_color_black() : lv_color_white()
#define LVGL_FOREGROUND IS_ENABLED(CONFIG_DONGLE_DISPLAY_INVERT) ? lv_color_white() : lv_color_black()
