manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: danielelombardo
      url-base: https://github.com/danielelombardo
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-config-keyb
      remote: danielelombardo
      revision: main
  self:
    path: config
